server.port=8080

spring.datasource.url=jdbc:sqlserver://sql_server_db:1433;databaseName=TestDB;encrypt=false
spring.datasource.username=sa
spring.datasource.password=Password_12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
